// Import Types
import { Metadata } from 'next';
// Import External Packages
// Import Components
import {
	SectionOuterContainer,
	SectionTitle,
	SectionDescription,
	SubSectionOuterContainer,
	SubSectionInnerContainer,
} from '@/ui/Section';
// Import Functions & Actions & Hooks & State
// Import Data
import { COMPANY_NAME } from '@/constants';
// Import Assets & Icons

export const metadata: Metadata = {
	title: `Privacy Policy | ${COMPANY_NAME} `,
	description: `Privacy Policy by ${COMPANY_NAME}.`,
	robots: 'noindex,nofollow',
};

export default function PrivacyPolicyPage() {
	return (
		<SectionOuterContainer id="Privacy Policy">
			<SectionTitle>Privacy Policy</SectionTitle>
			<SectionDescription>Last updated March 6, 2024</SectionDescription>
			<SubSectionOuterContainer className="max-w-3xl">
				<SubSectionInnerContainer className="items-start prose">
				<p className="inline">("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Finance Chest.</p>
              <div>
                <p className="inline">This Privacy Policy applies to our website,</p>
                <p className="inline"> https://financechest.io</p>
                <p className="inline">, and its associated subdomains (collectively, our "Service").</p>
              </div>
              <p><span>By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</span></p>
              <h1>Definitions and key terms</h1>
              <p><span>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</span></p>
              <ul>
                <li><span><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br /></span></li>
                <li><span><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to <a href="https://financechest.io">Financechest.io Inc</a>, <a href="https://maps.google.com/?q=1111b+S+Governors+Ave,+6469,+Dover,+DE+19904">1111b S Governors Ave, 6469, Dover, DE 19904</a> that is responsible for your information under this Privacy Policy.<br /></span></li>
                <li><span><strong>Country:</strong> where <a href="https://financechest.io">Finance Chest</a> or the owners/founders of <a href="https://financechest.io">Finance Chest</a> are based, in this case is <a href="https://financechest.io">United States</a>.<br /></span></li>
                <li><span><strong>Customer:</strong> refers to the company, organization or person that signs up to use the <a href="https://financechest.io">Finance Chest</a> Service to manage the relationships with your consumers or service users.<br /></span></li>
                <li><span><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit <a href="https://financechest.io">Finance Chest</a> and use the services.<br /></span></li>
                <li><span><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br /></span></li>
                <li><span><strong>Personnel:</strong> refers to those individuals who are employed by <a href="https://financechest.io">Finance Chest</a> or are under contract to perform a service on behalf of one of the parties.<br /></span></li>
                <li><span><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br /></span></li>
                <li><span><strong>Service:</strong> refers to the service provided by <a href="https://financechest.io">Finance Chest</a> as described in the relative terms (if available) and on this platform.<br /></span></li>
                <li><span><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br /></span></li>
                <li><span><strong>Website:</strong> <a href="https://financechest.io">Finance Chest</a>’s site, which can be accessed via this URL: <a href="https://financechest.io">https://financechest.io</a>.<br /></span></li>
                <li><span><strong>You:</strong> a person or entity that is registered with <a href="https://financechest.io">Finance Chest</a> to use the Services.<br /></span></li>
              </ul>
              <h1>What Information Do We Collect?</h1>
              <p><span>We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</span></p>
              <ul>
                <li><span>Name / Username</span></li>
                <li><span>Email Addresses</span></li>
                <li><span>Job Titles</span></li>
                <li><span>Password</span></li>
              </ul>
              <h1>How Do We Use The Information We Collect?</h1>
              <p><span>Any of the information we collect from you may be used in one of the following ways:</span></p>
              <ul>
                <li><span>To personalize your experience (your information helps us to better respond to your individual needs)</span></li>
                <li><span>To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</span></li>
                <li><span>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</span></li>
                <li><span>To process transactions</span></li>
                <li><span>To administer a contest, promotion, survey or other site feature</span></li>
                <li><span>To send periodic emails</span></li>
              </ul>
              <h1>When do we use customer information from third parties?</h1>
              <p><span>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</span></p>
              <h1>Do we share the information we collect with third parties?</h1>
              <p><span>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</span></p>
              <p><span>We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</span></p>
              <p><span>We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting for us and our advertisers.</span></p>
              <p><span>We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.</span></p>
              <h1>Where and when is information collected from customers and end users?</h1>
              <p><span>We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</span></p>
              <h1>How Do We Use Your Email Address?</h1>
              <p><span>By submitting your email address on this service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</span></p>
              <h1>How Long Do We Keep Your Information?</h1>
              <p><span>We keep your information only so long as we need it to provide <a href="https://financechest.io">Finance Chest</a> to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</span></p>
              <h1>How Do We Protect Your Information?</h1>
              <p><span>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to <a href="https://financechest.io">Finance Chest</a> or guarantee that your information on the service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</span></p>
              <h1>Could my information be transferred to other countries?</h1>
              <p><span><a href="https://financechest.io">Finance Chest</a> is incorporated in <a href="https://financechest.io">United States</a>. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</span></p>
              <h1>Is the information collected through the <a href="https://financechest.io">Finance Chest</a> Service secure?</h1>
              <p><span>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</span></p>
              <h1>Can I update or correct my information?</h1>
              <p><span>The rights you have to request updates or corrections to the information <a href="https://financechest.io">Finance Chest</a> collects depend on your relationship with <a href="https://financechest.io">Finance Chest</a>. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.</span></p>
              <h1>Personnel</h1>
              <p><span>If you are a <a href="https://financechest.io">Finance Chest</a> worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</span></p>
              <h1>Sale of Business</h1>
              <p><span>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of <a href="https://financechest.io">Finance Chest</a> or any of its Corporate Affiliates (as defined herein), or that portion of <a href="https://financechest.io">Finance Chest</a> or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</span></p>
              <h1>Affiliates</h1>
              <p><span>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with <a href="https://financechest.io">Finance Chest</a>, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</span></p>
              <h1>Governing Law</h1>
              <p><span>This Privacy Policy is governed by the laws of <a href="https://financechest.io">United States</a> without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.</span></p>
              <p><span>The laws of <a href="https://financechest.io">United States</a>, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.</span></p>
              <p><span>By using <a href="https://financechest.io">Finance Chest</a> or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.</span></p>
              <h1>Your Consent</h1>
              <p><span>We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</span></p>
              <h1>Links to Other Websites</h1>
              <p><span>This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by <a href="https://financechest.io">Finance Chest</a>. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</span></p>
              <h1>Advertising</h1>
              <p><span>This website may contain third party advertisements and links to third party sites. <a href="https://financechest.io">Finance Chest</a> does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties. Advertising keeps <a href="https://financechest.io">Finance Chest</a> and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive and as relevant as possible. Third party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by <a href="https://financechest.io">Finance Chest</a> of the third party sites, goods or services. <a href="https://financechest.io">Finance Chest</a> takes no responsibility for the content of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.</span></p>
              <h1>Cookies for Advertising</h1>
              <p><span>These cookies collect information over time about your online activity on the service and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.</span></p>
              <h1>Cookies</h1>
              <p><span><a href="https://financechest.io">Finance Chest</a> uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</span></p>
              <h1>Blocking and disabling cookies and similar technologies</h1>
              <p><span>Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.</span></p>
              <h1>California Residents</h1>
              <p><span>The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</span></p>
              <p><span>We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:</span></p>
              <ul>
                <li><span>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</span></li>
                <li><span>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</span></li>
                <li><span>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</span></li>
                <li><span>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</span></li>
              </ul>
              <p><span>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our contact information below.</span></p>
              <p><span>We do not sell the Personal Information of our users.</span></p>
              <p><span>For more information about these rights, please contact us.</span></p>
              <h1>California Online Privacy Protection Act (CalOPPA)</h1>
              <p><span>CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</span></p>
              <p><span>CalOPPA users have the following rights:</span></p>
              <ul>
                <li><span>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</span></li>
                <li><span>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</span></li>
                <li><span>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</span></li>
                <li><span>Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</span></li>
              </ul>
              <p><span>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at the contact information below.</span></p>
              <p><span>We do not sell the Personal Information of our users.</span></p>
              <p><span>For more information about these rights, please contact us.</span></p>
              <h1>Contact Us</h1>
              <p><span>Don't hesitate to contact us if you have any questions.</span></p>
              <ul>
                <li><span>Via this Link: <a href="https://financechest.io">https://financechest.io</a></span></li>
                <li><span>Via this Phone Number: +1-123-456-7890</span></li>
                <li><span>Via this Email Address: <a href="mailto:support@financechest.io">support@financechest.io</a></span></li>
              </ul>
              <p><span></span></p>        
				</SubSectionInnerContainer>
			</SubSectionOuterContainer>
		</SectionOuterContainer>
	);
}